formatter: "markdown table"

#recursive:
#  enabled: true
#  path: modules

output:
  file: "README.md"
  mode: replace
  template: |
    # OpenSearch
    
    Create an AWS managed OpenSearch cluster with supporting resources.
    
    {{ .Content }}

settings:
  lockfile: false
