name: tofu-ci
on:
  pull_request:
jobs:
  fmt-validate:
    needs: []
    name: Run format and validate
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +${{github.base_ref}}
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: 1.11.13
      - name: Tofu init
        run: tofu init
      - name: precommit run hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: tflint,markdown-link-check,terraform_docs,terraform_tfsec,checkov
        with:
          extra_args: --color=always --show-diff-on-failure --all-files
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: tofu -v

  lint:
    needs: []
    name: Run tflint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: 1.11.13
      - name: Tofu init
        run: tofu init
      - name: Run tflint with review comment on PR
        uses: reviewdog/action-tflint@ac21f7671251b29bbeb280ede595cb9c5b8710c7 # v1.26.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_init: true
          filter_mode: "nofilter"
          reporter: github-pr-review
          # tflint_rulesets: "aws"
          flags: --module

  security:
    name: Run tfsec
    needs: []
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      checks: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@ade3cd012981486a988fb56351d6d42b6bb7d3c9 # v1.31.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          flags: -tee
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@a8664e3a0549367977f0cda990a34311835c87c0 # v12.3123.0
        with:
          quiet: true
          skip_check: "CKV_TF_1,CKV_TF_2"
          download_external_modules: true
