name: terraform-ci
on:
  pull_request:
permissions:
  id-token: write
  actions: read
  checks: read
  contents: read
  pull-requests: write
jobs:
  ci:
    uses: SPHTech-Platform/platform-reusable-workflow/.github/workflows/terraform.yaml@main
    with:
      upload_sarif: false
      runner_label: platform-eng-ent-v2-dual
      skip_tflint_warn_for_changed_files: true
    secrets: inherit
